remote_theme: ngpaladi/texture

texture:
  title: Noah Paladino
  tagline: A blog about everything and nothing.
  date_format: "%b %-d, %Y"
  style: black
  show_excerpts: true

  social_links:
    twitter: noahpaladino
    github:  ngpaladi

show_excerpts: true
