title: Noah Paladino - Blog
author: Noah Paladino
email: noah@noahpaladino.com
description: > # this means to ignore newlines until "show_exerpts:"
  A simple blog about a variety of topics, from physics to computers.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Noah Paladino
  tagline: Blog
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle

  # generate social links in footer
  social_links:
    twitter: noahpaladino
    github:  ngpaladi
    # linkedIn: in/thelehhman
    # rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    instagram: noahpaladino
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll
    # homepage: https://www.noahpaladino.com/

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - index.md



plugins:
  - jekyll-seo-tag
#  - jekyll-feed
