remote_theme: ngpaladi/texture

title: Noah's Blog
author: Noah Paladino
email: noah@noahpaladino.com
description: > # this means to ignore newlines until "show_excerpts:"
  A blog about everything and nothing.

texture:
  title: Noah Paladino
  tagline: A blog about everything and nothing.
  date_format: "%b %-d, %Y"
  style: black

  social_links:
    twitter: noahpaladino
    github:  ngpaladi

